M48
; DRILL file {KiCad 7.0.2} date Fri Jan 10 16:22:40 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-10T16:22:40-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X56.0Y-65.0
X57.5Y-53.0
X57.5Y-175.5
X93.0Y-53.0
X93.0Y-175.5
X94.5Y-65.0
X95.75Y-115.25
T2
X58.8Y-149.2
X69.8Y-149.2
X81.0Y-149.2
X92.2Y-149.2
T0
M30
